### Все операции за сентябрь
GET http://localhost:8080/api/transactions/monthly?year=2026&month=9

### Только расходы
GET http://localhost:8080/api/transactions/monthly?year=2026&month=9&type=EXPENSE

### Только доходы
GET http://localhost:8080/api/transactions/monthly?year=2026&month=9&type=INCOME