spring.application.name=finplan-backend

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/finplan_db
spring.datasource.username=postgres
spring.datasource.password=${FINPLAN_DB_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
